//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

export type IconDefinitionBag = {
    /** The SVG markup for the icon for preview purposes in the icon picker. */
    iconSvg?: string | null;

    /** A list of search terms that can be used to find this icon. */
    searchTerms?: string[] | null;

    /** A CSS class added to the icon element to cause the correct icon to display. */
    styleClass?: string | null;

    /** The name of the icon */
    title?: string | null;
};
